using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Npgsql;

var builder = WebApplication.CreateBuilder(args);

// --- פתרון קסם לבעיות תאריכים (Legacy Fix) ---
// השורה הזו אומרת לשרת: "אל תהיה קשוח עם תאריכים, תקבל מה שאני נותן לך"
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

// --- לוגיקת חיבור ---
string connectionString = "";
var rawUrl = Environment.GetEnvironmentVariable("DATABASE_URL");

try 
{
    if (!string.IsNullOrWhiteSpace(rawUrl))
    {
        var uri = new Uri(rawUrl);
        var userInfo = uri.UserInfo.Split(':');
        
        var builderDb = new NpgsqlConnectionStringBuilder
        {
            Host = uri.Host,
            Port = uri.Port > 0 ? uri.Port : 5432,
            Username = userInfo[0],
            Password = userInfo[1],
            Database = uri.AbsolutePath.Trim('/'),
            SslMode = SslMode.Disable,
            TrustServerCertificate = true
        };
        connectionString = builderDb.ToString();
    }
}
catch (Exception) { }

builder.Services.AddDbContext<DietDb>(opt => 
{
    if (!string.IsNullOrEmpty(connectionString)) opt.UseNpgsql(connectionString);
});

builder.Services.AddCors();
var app = builder.Build();

app.UseCors(x => x.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
app.UseDefaultFiles();
app.UseStaticFiles();

// יצירת טבלאות
using (var scope = app.Services.CreateScope())
{
    if (!string.IsNullOrEmpty(connectionString))
    {
        var db = scope.ServiceProvider.GetRequiredService<DietDb>();
        try 
        {
            db.Database.EnsureCreated();
            // יצירה ידנית למקרה שהאוטומטי נכשל
            db.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""Meals"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text,
                    ""Calories"" integer,
                    ""Date"" timestamp without time zone,
                    CONSTRAINT ""PK_Meals"" PRIMARY KEY (""Id"")
                );
            ");
        } catch { }
    }
}

// --- API Endpoints ---

app.MapGet("/api/meals", async (DietDb db) => 
{
    if (string.IsNullOrEmpty(connectionString)) return Results.Ok(new List<Meal>());
    return Results.Ok(await db.Meals.OrderByDescending(m => m.Date).ToListAsync());
});

app.MapPost("/api/meals", async (DietDb db, [FromBody] Meal meal) => {
    if (string.IsNullOrEmpty(connectionString)) return Results.Problem("Database disconnected");
    try {
        // התיקון הגדול: שימוש ב-UTC (זמן עולמי)
        meal.Date = DateTime.UtcNow; 
        db.Meals.Add(meal);
        await db.SaveChangesAsync();
        return Results.Ok(meal);
    } catch (Exception ex) {
        return Results.Problem($"{ex.Message} Inner: {ex.InnerException?.Message}");
    }
});

app.MapDelete("/api/meals/{id}", async (DietDb db, int id) => {
    var meal = await db.Meals.FindAsync(id);
    if (meal is null) return Results.NotFound();
    db.Meals.Remove(meal);
    await db.SaveChangesAsync();
    return Results.Ok();
});

app.MapGet("/api/stats", async (DietDb db) => {
    if (string.IsNullOrEmpty(connectionString)) return Results.Ok(new { DailyCalories = 0 });
    // גם כאן משתמשים ב-UTC
    var today = DateTime.UtcNow.Date;
    try {
        var calories = await db.Meals.Where(m => m.Date >= today).SumAsync(m => m.Calories);
        return Results.Ok(new { DailyCalories = calories });
    } catch { return Results.Ok(new { DailyCalories = 0 }); }
});

app.Run();

public class DietDb : DbContext {
    public DietDb(DbContextOptions<DietDb> options) : base(options) {}
    public DbSet<Meal> Meals { get; set; }
}

public class Meal {
    public int Id { get; set; }
    public string Name { get; set; } = "";
    public int Calories { get; set; }
    public DateTime Date { get; set; }
}
