using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using System.Security.Cryptography; // ספריית האבטחה
using System.Text;

var builder = WebApplication.CreateBuilder(args);

// הגדרת תאריכים
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

// --- חיבור ל-DB ---
string connectionString = "";
var rawUrl = Environment.GetEnvironmentVariable("DATABASE_URL");
try {
    if (!string.IsNullOrWhiteSpace(rawUrl)) {
        var uri = new Uri(rawUrl);
        var userInfo = uri.UserInfo.Split(':');
        var builderDb = new NpgsqlConnectionStringBuilder {
            Host = uri.Host, Port = uri.Port > 0 ? uri.Port : 5432,
            Username = userInfo[0], Password = userInfo[1],
            Database = uri.AbsolutePath.Trim('/'),
            SslMode = SslMode.Disable, TrustServerCertificate = true
        };
        connectionString = builderDb.ToString();
    }
} catch { }

builder.Services.AddDbContext<DietDb>(opt => {
    if (!string.IsNullOrEmpty(connectionString)) opt.UseNpgsql(connectionString);
});
builder.Services.AddCors();
var app = builder.Build();
app.UseCors(x => x.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
app.UseDefaultFiles();
app.UseStaticFiles();

// --- יצירת טבלאות (משתמשים + ארוחות) ---
using (var scope = app.Services.CreateScope()) {
    if (!string.IsNullOrEmpty(connectionString)) {
        var db = scope.ServiceProvider.GetRequiredService<DietDb>();
        try { 
            db.Database.EnsureCreated();
            
            // יצירת טבלת משתמשים אם לא קיימת
            db.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""Users"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Email"" text NOT NULL,
                    ""PasswordHash"" bytea NOT NULL,
                    ""PasswordSalt"" bytea NOT NULL,
                    CONSTRAINT ""PK_Users"" PRIMARY KEY (""Id"")
                );
            ");
            
            // עדכון טבלת ארוחות שתכלול UserId (קישור למשתמש)
            // הערה: בשלב ראשון אנחנו רק מוודאים שהטבלה קיימת
             db.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""Meals"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text,
                    ""Calories"" integer,
                    ""Date"" timestamp without time zone,
                    ""UserId"" integer DEFAULT 0, 
                    CONSTRAINT ""PK_Meals"" PRIMARY KEY (""Id"")
                );
            ");

        } catch (Exception ex) { Console.WriteLine("DB Init Error: " + ex.Message); }
    }
}

// --- לוגיקת אבטחה (החלק המקצועי) ---
// פונקציה ליצירת Hash ו-Salt
void CreatePasswordHash(string password, out byte[] passwordHash, out byte[] passwordSalt)
{
    using (var hmac = new HMACSHA512())
    {
        passwordSalt = hmac.Key; // המפתח האקראי (המלח)
        passwordHash = hmac.ComputeHash(Encoding.UTF8.GetBytes(password)); // הערבוב
    }
}

// פונקציה לבדיקת סיסמה בכניסה
bool VerifyPasswordHash(string password, byte[] storedHash, byte[] storedSalt)
{
    using (var hmac = new HMACSHA512(storedSalt))
    {
        var computedHash = hmac.ComputeHash(Encoding.UTF8.GetBytes(password));
        return computedHash.SequenceEqual(storedHash); // האם התוצאה זהה?
    }
}

// --- API: משתמשים (Auth) ---

// הרשמה
app.MapPost("/api/auth/register", async (DietDb db, [FromBody] UserRegisterDto request) => {
    if (await db.Users.AnyAsync(u => u.Email == request.Email))
        return Results.BadRequest("המייל הזה כבר קיים במערכת");

    CreatePasswordHash(request.Password, out byte[] passwordHash, out byte[] passwordSalt);

    var user = new User {
        Email = request.Email,
        PasswordHash = passwordHash,
        PasswordSalt = passwordSalt
    };

    db.Users.Add(user);
    await db.SaveChangesAsync();

    return Results.Ok(new { message = "נרשמת בהצלחה! עכשיו אפשר להתחבר." });
});

// התחברות
app.MapPost("/api/auth/login", async (DietDb db, [FromBody] UserLoginDto request) => {
    var user = await db.Users.FirstOrDefaultAsync(u => u.Email == request.Email);
    if (user == null) return Results.BadRequest("משתמש לא נמצא");

    if (!VerifyPasswordHash(request.Password, user.PasswordHash, user.PasswordSalt))
        return Results.BadRequest("סיסמה שגויה");

    // כאן אנחנו מחזירים את ה-ID של המשתמש כדי שהדפדפן יזכור מי הוא
    return Results.Ok(new { userId = user.Id, email = user.Email, message = "התחברת בהצלחה!" });
});


// --- API: ארוחות (מחובר למשתמש) ---

app.MapGet("/api/meals", async (DietDb db, int userId) => {
    // מביא רק את הארוחות של המשתמש הספציפי
    if (userId == 0) return Results.Ok(new List<Meal>());
    return Results.Ok(await db.Meals.Where(m => m.UserId == userId).OrderByDescending(m => m.Date).ToListAsync());
});

app.MapPost("/api/meals", async (DietDb db, [FromBody] Meal meal) => {
    if (meal.UserId == 0) return Results.BadRequest("שגיאה: לא מחובר");
    
    if (meal.Date == default) meal.Date = DateTime.Now; 
    db.Meals.Add(meal);
    await db.SaveChangesAsync();
    return Results.Ok(meal);
});

app.MapDelete("/api/meals/{id}", async (DietDb db, int id) => {
    var meal = await db.Meals.FindAsync(id);
    if (meal is null) return Results.NotFound();
    db.Meals.Remove(meal);
    await db.SaveChangesAsync();
    return Results.Ok();
});

app.MapGet("/api/stats", async (DietDb db, int userId) => {
    if (userId == 0) return Results.Ok(new { DailyCalories = 0 });
    
    // סטטיסטיקה לפי זמן ישראל למשתמש הספציפי
    var today = DateTime.UtcNow.AddHours(3).Date; 
    var calories = await db.Meals
        .Where(m => m.UserId == userId && m.Date >= today)
        .SumAsync(m => m.Calories);
        
    return Results.Ok(new { DailyCalories = calories });
});

app.Run();

// --- Models ---

public class DietDb : DbContext {
    public DietDb(DbContextOptions<DietDb> options) : base(options) {}
    public DbSet<Meal> Meals { get; set; }
    public DbSet<User> Users { get; set; } // טבלה חדשה
}

public class User {
    public int Id { get; set; }
    public string Email { get; set; } = string.Empty;
    public byte[] PasswordHash { get; set; } // לא שומרים string!
    public byte[] PasswordSalt { get; set; }
}

public class Meal {
    public int Id { get; set; }
    public string Name { get; set; } = "";
    public int Calories { get; set; }
    public DateTime Date { get; set; }
    public int UserId { get; set; } // המפתח הזר (למי שייכת הארוחה)
}

// מחלקות עזר לקבלת מידע מהלקוח (DTO = Data Transfer Object)
public class UserRegisterDto {
    public string Email { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
}

public class UserLoginDto {
    public string Email { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
}
