using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using System.Security.Cryptography;
using System.Text;
// החיבורים החדשים לקבצים שיצרנו:
using FitnessPro.Data;
using FitnessPro.Models;

var builder = WebApplication.CreateBuilder(args);

// הגדרת תאריכים
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

// --- חיבור ל-DB ---
string connectionString = "";
var rawUrl = Environment.GetEnvironmentVariable("DATABASE_URL");
try {
    if (!string.IsNullOrWhiteSpace(rawUrl)) {
        var uri = new Uri(rawUrl);
        var userInfo = uri.UserInfo.Split(':');
        var builderDb = new NpgsqlConnectionStringBuilder {
            Host = uri.Host, Port = uri.Port > 0 ? uri.Port : 5432,
            Username = userInfo[0], Password = userInfo[1],
            Database = uri.AbsolutePath.Trim('/'),
            SslMode = SslMode.Disable, TrustServerCertificate = true
        };
        connectionString = builderDb.ToString();
    }
} catch { }

builder.Services.AddDbContext<DietDb>(opt => {
    if (!string.IsNullOrEmpty(connectionString)) opt.UseNpgsql(connectionString);
});
builder.Services.AddCors();
var app = builder.Build();
app.UseCors(x => x.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
app.UseDefaultFiles();
app.UseStaticFiles();

// --- יצירת טבלאות ועדכונים (Migration פשוט) ---
using (var scope = app.Services.CreateScope()) {
    if (!string.IsNullOrEmpty(connectionString)) {
        var db = scope.ServiceProvider.GetRequiredService<DietDb>();
        try { 
            db.Database.EnsureCreated();
            
            // יצירת טבלאות בסיסית אם לא קיימות
            db.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""Users"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Email"" text NOT NULL,
                    ""PasswordHash"" bytea NOT NULL,
                    ""PasswordSalt"" bytea NOT NULL,
                    CONSTRAINT ""PK_Users"" PRIMARY KEY (""Id"")
                );
            ");
            
             db.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""Meals"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text,
                    ""Calories"" integer,
                    ""Date"" timestamp without time zone,
                    ""UserId"" integer DEFAULT 0, 
                    ""MealType"" text, 
                    CONSTRAINT ""PK_Meals"" PRIMARY KEY (""Id"")
                );
            ");

        } catch (Exception ex) { 
            Console.WriteLine("DB Init Error: " + ex.Message); 
        }
    }
}

// --- פונקציות אבטחה (Helpers) ---
void CreatePasswordHash(string password, out byte[] passwordHash, out byte[] passwordSalt)
{
    using (var hmac = new HMACSHA512())
    {
        passwordSalt = hmac.Key;
        passwordHash = hmac.ComputeHash(Encoding.UTF8.GetBytes(password));
    }
}

bool VerifyPasswordHash(string password, byte[] storedHash, byte[] storedSalt)
{
    using (var hmac = new HMACSHA512(storedSalt))
    {
        var computedHash = hmac.ComputeHash(Encoding.UTF8.GetBytes(password));
        return computedHash.SequenceEqual(storedHash);
    }
}

// --- API Endpoints ---

// הרשמה
app.MapPost("/api/auth/register", async (DietDb db, [FromBody] UserRegisterDto request) => {
    if (string.IsNullOrWhiteSpace(request.Email) || !request.Email.Contains("@"))
        return Results.BadRequest("כתובת המייל אינה תקינה");

    if (string.IsNullOrWhiteSpace(request.Password) || request.Password.Length < 8)
        return Results.BadRequest("הסיסמה חייבת להכיל לפחות 8 תווים");

    if (await db.Users.AnyAsync(u => u.Email == request.Email))
        return Results.BadRequest("המייל הזה כבר רשום במערכת");

    CreatePasswordHash(request.Password, out byte[] passwordHash, out byte[] passwordSalt);

    var user = new User {
        Email = request.Email,
        PasswordHash = passwordHash,
        PasswordSalt = passwordSalt
    };

    db.Users.Add(user);
    await db.SaveChangesAsync();

    return Results.Ok(new { message = "נרשמת בהצלחה!" });
});

// התחברות
app.MapPost("/api/auth/login", async (DietDb db, [FromBody] UserLoginDto request) => {
    var user = await db.Users.FirstOrDefaultAsync(u => u.Email == request.Email);
    if (user == null) return Results.BadRequest("משתמש לא נמצא");

    if (!VerifyPasswordHash(request.Password, user.PasswordHash, user.PasswordSalt))
        return Results.BadRequest("סיסמה שגויה");

    return Results.Ok(new { userId = user.Id, email = user.Email });
});

// קבלת ארוחות
app.MapGet("/api/meals", async (DietDb db, int userId) => {
    if (userId == 0) return Results.Ok(new List<Meal>());
    return Results.Ok(await db.Meals.Where(m => m.UserId == userId).OrderByDescending(m => m.Date).ToListAsync());
});

// הוספת ארוחה
app.MapPost("/api/meals", async (DietDb db, [FromBody] Meal meal) => {
    if (meal.UserId == 0) return Results.BadRequest("שגיאה: לא מחובר");
    
    if (meal.Date == default) meal.Date = DateTime.UtcNow.AddHours(3);
    if (string.IsNullOrEmpty(meal.MealType)) meal.MealType = "snack";

    db.Meals.Add(meal);
    await db.SaveChangesAsync();
    return Results.Ok(meal);
});

// מחיקת ארוחה
app.MapDelete("/api/meals/{id}", async (DietDb db, int id) => {
    var meal = await db.Meals.FindAsync(id);
    if (meal is null) return Results.NotFound();
    db.Meals.Remove(meal);
    await db.SaveChangesAsync();
    return Results.Ok();
});

// סטטיסטיקה יומית
app.MapGet("/api/stats", async (DietDb db, int userId) => {
    if (userId == 0) return Results.Ok(new { DailyCalories = 0 });
    
    // כאן אפשר להשתמש בחישוב של UTC אם רוצים, אבל כרגע זה פשוט סוכם לפי מה שיש ב-DB
    var today = DateTime.UtcNow.AddHours(3).Date; 
    var calories = await db.Meals
        .Where(m => m.UserId == userId && m.Date >= today)
        .SumAsync(m => m.Calories);
        
    return Results.Ok(new { DailyCalories = calories });
});

app.Run();
